#!/usr/bin/env python3
"""
json_to_pine.py — convert an account orders JSON export into a ready-to-paste
TradingView Pine Script (v6) that plots the working orders on the chart.

Pine Script cannot read files at runtime, so this script bakes the orders into
the .pine source as arrays. Re-run it whenever you have a fresh JSON export.

Usage:
    python3 json_to_pine.py orders.json                 # writes plot_orders.pine
    python3 json_to_pine.py orders.json my_output.pine  # custom output name
    python3 json_to_pine.py orders.json -               # print to stdout

Notes:
  - The "root" is derived from symbolId (e.g. "F.US.MGC" -> "MGC"). The Pine
    script filters orders by matching this root against the chart symbol, so
    MGC orders only appear on a gold chart, SIL on silver, etc.
  - For each order it uses limitPrice if present, otherwise stopPrice.
  - side: 0 = buy (green), 1 = sell (red).
  - By default only working orders (status == 1) are included; use --all to
    include every order in the file.
"""

import json
import sys


def root_from_order(o):
    """Derive a short symbol root, e.g. 'F.US.MGC' -> 'MGC'."""
    sym = o.get("symbolId") or ""
    if sym:
        return sym.split(".")[-1]
    # fallback: parse contractId like 'CON.F.US.MGC.Q26'
    cid = o.get("contractId") or ""
    parts = [p for p in cid.split(".") if p]
    if len(parts) >= 2:
        return parts[-2]
    return "UNKNOWN"


def order_price(o):
    p = o.get("limitPrice")
    if p is None:
        p = o.get("stopPrice")
    return p


def collect_orders(data, include_all=False):
    rows = []
    for acct in data.get("accounts", []):
        for o in acct.get("orders", []):
            if not include_all and o.get("status") != 1:
                continue
            price = order_price(o)
            if price is None:
                continue
            rows.append({
                "root": root_from_order(o),
                "price": price,
                "side": int(o.get("side", 0)),
                "size": int(o.get("size", 0)),
            })
    return rows


def fmt_num(x):
    """Compact numeric string (no trailing zeros) for Pine literals."""
    s = repr(float(x))
    if s.endswith(".0"):
        s = s[:-2]
    return s


def pine_array(name, ptype, values, quote=False):
    if not values:
        return f"var {ptype}[] {name} = array.new<{ptype}>()"
    if quote:
        items = ",".join('"' + str(v) + '"' for v in values)
    else:
        items = ",".join(values)
    return f"var {ptype}[] {name} = array.from({items})"


def build_pine(rows, captured_at=None):
    roots = [r["root"] for r in rows]
    prices = [fmt_num(r["price"]) for r in rows]
    sides = [str(r["side"]) for r in rows]
    sizes = [str(r["size"]) for r in rows]

    distinct = sorted(set(roots))
    title = "Order Map (" + " / ".join(distinct) + ")" if distinct else "Order Map"
    cap = f" (captured {captured_at})" if captured_at else ""

    return f'''//@version=6
// =============================================================================
// {title} — auto-generated by json_to_pine.py{cap}
// =============================================================================
// Pine Script cannot read external files at runtime, so the orders below are
// embedded directly from your JSON. Re-run json_to_pine.py to refresh.
//
// Each order is drawn as a horizontal line at its price, extended right, with
// a label showing side, size and price.
//   - side 0 (buy / long stop)   -> green
//   - side 1 (sell / short stop)  -> red
// Orders are filtered by the chart's symbol root (e.g. MGC, SIL).
// =============================================================================

indicator("{title}", overlay = true, max_lines_count = 500, max_labels_count = 500)

// ---- Inputs -----------------------------------------------------------------
showAll      = input.bool(false, "Show all symbols (ignore symbol filter)")
lineWidth    = input.int(1, "Line width", minval = 1, maxval = 5)
lookbackBars = input.int(200, "Line start (bars back)", minval = 10, maxval = 5000)
buyColor     = input.color(color.new(color.green, 0), "Buy / long stop")
sellColor    = input.color(color.new(color.red, 0),   "Sell / short stop")
labelSize    = input.string(size.small, "Label size", options = [size.tiny, size.small, size.normal, size.large])

// ---- Embedded order data (from JSON) ----------------------------------------
// root, price, side (0 buy / 1 sell), size
{pine_array("roots", "string", roots, quote=True)}
{pine_array("prices", "float", prices)}
{pine_array("sides", "int", sides)}
{pine_array("sizes", "int", sizes)}

// ---- Draw on the last bar only ----------------------------------------------
var line[]  drawnLines  = array.new_line()
var label[] drawnLabels = array.new_label()

if barstate.islast
    for ln in drawnLines
        line.delete(ln)
    for lb in drawnLabels
        label.delete(lb)
    array.clear(drawnLines)
    array.clear(drawnLabels)

    x1 = bar_index - lookbackBars
    x2 = bar_index + 20

    for i = 0 to array.size(prices) - 1
        root = array.get(roots, i)
        matches = showAll or str.contains(syminfo.ticker, root) or str.contains(syminfo.prefix, root)
        if matches
            price = array.get(prices, i)
            side  = array.get(sides, i)
            sz    = array.get(sizes, i)
            col   = side == 0 ? buyColor : sellColor
            txt   = (side == 0 ? "BUY " : "SELL ") + str.tostring(sz) + " @ " + str.tostring(price)

            ln = line.new(x1, price, x2, price, xloc = xloc.bar_index, extend = extend.right, color = col, width = lineWidth, style = line.style_solid)
            array.push(drawnLines, ln)

            lb = label.new(x2, price, text = txt, xloc = xloc.bar_index, style = label.style_label_left, color = col, textcolor = color.white, size = labelSize)
            array.push(drawnLabels, lb)
'''


def main():
    args = [a for a in sys.argv[1:]]
    include_all = "--all" in args
    args = [a for a in args if a != "--all"]

    if not args:
        print(__doc__)
        sys.exit(1)

    in_path = args[0]
    out_path = args[1] if len(args) > 1 else "plot_orders.pine"

    with open(in_path, "r") as f:
        data = json.load(f)

    rows = collect_orders(data, include_all=include_all)
    if not rows:
        print("No matching orders found in JSON.", file=sys.stderr)
        sys.exit(2)

    pine = build_pine(rows, captured_at=data.get("captured_at"))

    if out_path == "-":
        sys.stdout.write(pine)
    else:
        with open(out_path, "w") as f:
            f.write(pine)
        print(f"Wrote {len(rows)} orders to {out_path}")


if __name__ == "__main__":
    main()
